server:
  port: 8761

spring:
  application:
    name : eureka-server

eureka:
  client:
    register-with-eureka: false  # we don't register Eureka service with itself
    fetch-registry: false # Do not try to download the registry of services from the Eureka server." This means your application won't know about other services registered with Eureka.

  management:
    endpoints:
      web:
        exposure:
          include: health